// Sales OS — OPTIONAL VIDEO SLOTS for the two prospect/client-facing pages.
// Files under functions/_lib are NOT routed.
//
// WHAT THIS IS FOR. The self-serve rails (/for/<token> and /start/<token>) answer in words
// everything a prospect or a new account would otherwise email Dayan about. Turo's onboarding
// pairs those words with a short orientation video, and that is the shape he asked for — but the
// video does not exist yet and cannot be generated. So each section gets a SLOT: an owner-settable
// URL that, while empty, renders NOTHING AT ALL. The prose above it is the page whether or not a
// file ever appears, and turning a video on later is one settings save, not a deploy.
//
// FOUR RULES, AND THEY ARE WHY THIS FILE EXISTS RATHER THAN AN INLINE <video> ON EACH PAGE:
//   1. NEVER AUTOPLAY. These pages open on a phone in a clinic corridor. A video that starts
//      talking by itself is the reason people close a tab.
//   2. POSTER-FRAMED AND CLICK-TO-PLAY. `preload="none"` means the bytes are not fetched until a
//      human presses play, so a 40 MB file costs a visitor nothing until they want it. The poster
//      is a still image and is all that loads.
//   3. CAPTIONS ARE A FIRST-CLASS FIELD, not an afterthought — a sound-off viewer is the normal
//      case here, and native controls give them the mute. <track> only accepts WebVTT, which is
//      why the validator insists on a .vtt file rather than accepting any URL and failing silently
//      in the browser.
//   4. NOTHING BREAKS WHEN A URL IS WRONG. A <video> whose source 404s still shows its poster and
//      its fallback link; a slot with no URL emits an empty string that disappears into the markup.
//
// CONTENT-SECURITY-POLICY NOTE. public/_headers sets `default-src 'self'` with no `media-src`,
// which would block an off-origin video — but Cloudflare Pages does NOT apply _headers to
// responses generated by Pages Functions, and both pages that render these slots are Functions
// that set their own headers. So an https:// URL on any host plays. If either page is ever turned
// into a static asset, a `media-src` entry has to be added to _headers first.
import { escHtml } from '../email.js';

// The slots, in the order the owner meets them, each with the ONE page that renders it. A slot
// with two homes would mean the same video playing twice in one session, so each has exactly one.
export const MEDIA_SLOTS = {
  how_it_works: { label: 'How it works', where: 'Prospect landing page — the “How it works” section' },
  faq: { label: 'Questions', where: 'Prospect landing page — above the questions' },
  orientation: { label: 'Orientation', where: 'Account onboarding page — the first thing a new site sees' },
  onboarding: { label: 'Your first week', where: 'Account onboarding page — the first-week walkthrough' },
};

const EMPTY_SLOT = { url: '', poster: '', caption: '', captions_url: '', captions_lang: 'en' };

export const DEFAULT_MEDIA = Object.fromEntries(Object.keys(MEDIA_SLOTS).map((k) => [k, { ...EMPTY_SLOT }]));

// Only the languages Añejo actually publishes in. An unknown code is refused rather than shipped
// to a screen reader as a label nobody can read.
export const CAPTION_LANGS = { en: 'English', es: 'Español' };

const VIDEO_TYPES = { mp4: 'video/mp4', webm: 'video/webm', ogv: 'video/ogg', mov: 'video/quicktime', m4v: 'video/mp4' };

/**
 * A URL we are willing to put in a src attribute: an absolute https:// URL, or a same-origin
 * absolute path. Everything else — javascript:, data:, http://, a protocol-relative //host, a
 * traversal — comes back empty, which the renderer reads as "no media".
 */
export function safeMediaUrl(v) {
  const s = String(v == null ? '' : v).trim();
  if (!s || s.length > 500 || s.includes('..') || /[\s<>"']/.test(s)) return '';
  if (s.startsWith('//')) return '';
  if (s.startsWith('/')) return s;
  if (!/^https:\/\/[^/]+\//i.test(s)) return '';
  try { return new URL(s).protocol === 'https:' ? s : ''; } catch { return ''; }
}

/** One slot as the pages want it: every field clean, or null when there is no video to show. */
export function mediaSlot(media, slot) {
  const raw = media && typeof media === 'object' ? media[slot] : null;
  if (!raw || typeof raw !== 'object') return null;
  const url = safeMediaUrl(raw.url);
  if (!url) return null;
  const lang = Object.prototype.hasOwnProperty.call(CAPTION_LANGS, raw.captions_lang) ? raw.captions_lang : 'en';
  return {
    url,
    poster: safeMediaUrl(raw.poster),
    caption: String(raw.caption || '').trim().slice(0, 300),
    captions_url: safeMediaUrl(raw.captions_url),
    captions_lang: lang,
    captions_label: CAPTION_LANGS[lang],
  };
}

/**
 * Refuse a bad save with a sentence the owner can act on — the settings API returns this verbatim.
 * null means "save it". Unknown slot names are named rather than dropped: silently ignoring a
 * typo'd key is how a video gets uploaded, configured, and never appears anywhere.
 */
export function validateMedia(value) {
  if (!value || typeof value !== 'object' || Array.isArray(value)) return 'Media settings must be an object.';
  for (const [slot, cfg] of Object.entries(value)) {
    const meta = MEDIA_SLOTS[slot];
    if (!meta) return `Unknown media slot “${slot}”. The slots are: ${Object.keys(MEDIA_SLOTS).join(', ')}.`;
    if (cfg == null) continue;
    if (typeof cfg !== 'object' || Array.isArray(cfg)) return `The ${meta.label} slot must be an object.`;
    const url = String(cfg.url || '').trim();
    const poster = String(cfg.poster || '').trim();
    const captions = String(cfg.captions_url || '').trim();
    if (url && !safeMediaUrl(url)) return `The ${meta.label} video URL must be an https:// address or a path on this site.`;
    if (poster && !safeMediaUrl(poster)) return `The ${meta.label} poster image URL must be an https:// address or a path on this site.`;
    if (captions && !safeMediaUrl(captions)) return `The ${meta.label} captions URL must be an https:// address or a path on this site.`;
    // <track> reads WebVTT and nothing else. Accepting an .srt here would store a setting that can
    // only ever fail in the browser, with no error anyone would see.
    if (captions && !/\.vtt(\?|#|$)/i.test(captions)) return `The ${meta.label} captions file must be a WebVTT (.vtt) file.`;
    if (cfg.captions_lang && !CAPTION_LANGS[cfg.captions_lang]) return `Captions language must be one of: ${Object.keys(CAPTION_LANGS).join(', ')}.`;
    // A poster or a caption with no video is a half-filled slot that renders nothing. Say so now,
    // rather than leaving the owner to wonder why the page did not change.
    if (!url && (poster || captions)) return `Add the ${meta.label} video URL — a poster or captions on their own render nothing.`;
    if (String(cfg.caption || '').length > 300) return `The ${meta.label} caption is too long (300 characters).`;
  }
  return null;
}

// Styles for the slot. Exported as a string so both pages render an identical player instead of
// drifting apart — the rest of each page's CSS is its own.
export const MEDIA_CSS = `
.vid{margin:0 0 16px}
.vid video{width:100%;max-width:100%;display:block;background:#0D0D0D;border-radius:12px;border:1px solid var(--line);aspect-ratio:16/9}
.vid figcaption{font-size:13px;color:var(--muted);margin-top:7px;line-height:1.5}
.vid .fb{padding:14px;color:var(--muted);font-size:14px}
.vid .fb a{color:var(--gold-deep)}`;

/**
 * The player, or '' when the slot is empty. `label` names the video for a screen reader, since the
 * caption is optional and a bare <video> announces itself as nothing at all.
 */
export function mediaSlotHtml(media, slot, { label = '' } = {}) {
  const m = mediaSlot(media, slot);
  if (!m) return '';
  const e = escHtml;
  const ext = (m.url.split(/[?#]/)[0].split('.').pop() || '').toLowerCase();
  const type = VIDEO_TYPES[ext] ? ` type="${VIDEO_TYPES[ext]}"` : '';
  const aria = label || (MEDIA_SLOTS[slot] && MEDIA_SLOTS[slot].label) || 'Video';
  return `<figure class="vid">`
    + `<video controls playsinline preload="none"${m.poster ? ` poster="${e(m.poster)}"` : ''} aria-label="${e(aria)}">`
    + `<source src="${e(m.url)}"${type}>`
    + (m.captions_url ? `<track kind="captions" src="${e(m.captions_url)}" srclang="${e(m.captions_lang)}" label="${e(m.captions_label)}" default>` : '')
    + `<p class="fb">This browser cannot play the video. <a href="${e(m.url)}" rel="noopener">Open it in a new tab</a>.</p>`
    + `</video>`
    + (m.caption ? `<figcaption>${e(m.caption)}</figcaption>` : '')
    + `</figure>`;
}
