import test from 'node:test';import assert from 'node:assert/strict';import sharp from 'sharp';
import {admitSourceColor} from './source-color-admission.mjs';
const {crc32}=globalThis.AnejoImageOrientation;
const fixture=async(format='png',profile=null,orientation=1)=>{let p=sharp({create:{width:40,height:20,channels:3,background:'#985332'}});if(profile)p=p.withIccProfile(profile);let bytes=new Uint8Array(await p[format]().toBuffer());if(orientation!==1){const tiff=Buffer.from('49492a0008000000010012010300010000000100000000000000','hex');tiff.writeUInt16LE(orientation,18);if(format==='png')bytes=add(bytes,chunk('eXIf',tiff));else{const payload=Buffer.concat([Buffer.from('Exif\0\0'),tiff]),segment=Buffer.alloc(payload.length+4);segment[0]=255;segment[1]=225;segment.writeUInt16BE(payload.length+2,2);segment.set(payload,4);bytes=new Uint8Array(Buffer.concat([bytes.subarray(0,2),segment,bytes.subarray(2)]));}}return bytes;};
function chunk(type,data){const b=Buffer.alloc(data.length+12);b.writeUInt32BE(data.length);b.write(type,4);b.set(data,8);b.writeUInt32BE(crc32(b.subarray(4,-4)),b.length-4);return b;}
const add=(png,...chunks)=>new Uint8Array(Buffer.concat([png.subarray(0,33),...chunks,png.subarray(33)]));
const refused=(bytes,reason)=>assert.throws(()=>admitSourceColor(bytes),e=>e.message==='source_color_normalization_required'&&e.reason===reason);
test('untagged RGB admits assumption only and leaves original unchanged',async()=>{for(const format of ['png','jpeg']){const b=await fixture(format),copy=b.slice(),r=admitSourceColor(b);assert.equal(r.colorStatus,'assumed_srgb');assert.equal(r.conversionPerformed,false);assert.equal(r.visualReviewRequired,true);assert.equal(r.authenticity,'unverified');assert.deepEqual(b,copy);}});
test('actual P3 and sRGB profiles both require conversion rather than stripping',async()=>{for(const format of ['png','jpeg'])for(const profile of ['p3','srgb'])refused(await fixture(format,profile),'embedded_icc_requires_conversion');});
test('explicit PNG sRGB distinguished; malformed duplicate and bad CRC refused',async()=>{const b=await fixture();assert.equal(admitSourceColor(add(b,chunk('sRGB',Buffer.from([0])))).colorStatus,'declared_srgb');for(const c of [chunk('sRGB',Buffer.from([4])),chunk('sRGB',Buffer.from([]))])assert.throws(()=>admitSourceColor(add(b,c)),/source_color_invalid/);const bad=chunk('sRGB',Buffer.from([0]));bad[bad.length-1]^=1;assert.throws(()=>admitSourceColor(add(b,bad)),/source_color_invalid/);assert.throws(()=>admitSourceColor(add(b,chunk('sRGB',Buffer.from([0])),chunk('sRGB',Buffer.from([0])))),/source_color_invalid/);});
test('HDR animation and nonstandard gamma/chromaticity refused',async()=>{const b=await fixture();for(const name of ['cICP','mDCv','cLLi','acTL','fcTL','fdAT'])refused(add(b,chunk(name,Buffer.from([0]))),'hdr_or_animated_png');const gamma=Buffer.alloc(4);gamma.writeUInt32BE(45455);assert.equal(admitSourceColor(add(b,chunk('gAMA',gamma))).colorStatus,'assumed_srgb');gamma.writeUInt32BE(100000);refused(add(b,chunk('gAMA',gamma)),'nonstandard_png_gamma');refused(add(b,chunk('cHRM',Buffer.alloc(32))),'nonstandard_png_chromaticities');});
test('actual CMYK and high-depth sources refused',async()=>{const p=()=>sharp({create:{width:40,height:20,channels:3,background:'#985332'}});const cmyk=new Uint8Array(await p().toColourspace('cmyk').jpeg().toBuffer());assert.throws(()=>admitSourceColor(cmyk),/source_color_normalization_required/);refused(new Uint8Array(await p().toColourspace('rgb16').png().toBuffer()),'png_requires_8bit_rgb_or_rgba');});
test('all eight orientations retain meaning; corrupt and oversized headers refused',async()=>{for(const format of ['png','jpeg'])for(let o=1;o<=8;o++)assert.equal(admitSourceColor(await fixture(format,null,o)).orientation,o);const b=await fixture();assert.throws(()=>admitSourceColor(b.subarray(0,-5)),/source_color_invalid/);assert.throws(()=>admitSourceColor(new Uint8Array(5*1024*1024+1)),/source_color_invalid/);});
test('JPEG auxiliary gain-map metadata and PNG contradictory color declarations cannot appear supported',async()=>{
 const jpg=await fixture('jpeg');for(const marker of [225,226,235]){const payload=Buffer.from('uninterpreted HDR gain map'),segment=Buffer.alloc(payload.length+4);segment[0]=255;segment[1]=marker;segment.writeUInt16BE(payload.length+2,2);segment.set(payload,4);assert.throws(()=>admitSourceColor(new Uint8Array(Buffer.concat([jpg.subarray(0,2),segment,jpg.subarray(2)]))),/source_color_normalization_required/);}
 const profiled=await fixture('png','p3');refused(add(profiled,chunk('sRGB',Buffer.from([0]))),'embedded_icc_requires_conversion');
 const valid=Buffer.alloc(32);[31270,32900,64000,33000,30000,60000,15000,6000].forEach((v,i)=>valid.writeUInt32BE(v,i*4));assert.equal(admitSourceColor(add(await fixture(),chunk('cHRM',valid))).colorStatus,'assumed_srgb');
});
function photoshopJPEG(jpg,id,data=Buffer.alloc(0),name=Buffer.alloc(0)){
 const named=Buffer.concat([Buffer.from([name.length]),name,...((1+name.length)%2?[Buffer.from([0])]:[])]),resource=Buffer.alloc(6);resource.write('8BIM');resource.writeUInt16BE(id,4);const length=Buffer.alloc(4);length.writeUInt32BE(data.length);const payload=Buffer.concat([Buffer.from('Photoshop 3.0\0'),resource,named,length,data,...(data.length%2?[Buffer.from([0])]:[])]),segment=Buffer.alloc(payload.length+4);segment[0]=255;segment[1]=237;segment.writeUInt16BE(payload.length+2,2);segment.set(payload,4);return new Uint8Array(Buffer.concat([jpg.subarray(0,2),segment,jpg.subarray(2)]));
}
test('existing website photo with bounded IPTC and digest resources remains explicitly assumed sRGB',async()=>{
 const {readFile}=await import('node:fs/promises'),b=new Uint8Array(await readFile(new URL('./assets/source.jpg',import.meta.url))),copy=b.slice();const r=admitSourceColor(b);assert.equal(r.colorStatus,'assumed_srgb');assert.equal(r.conversionPerformed,false);assert.deepEqual(b,copy);
});
test('Photoshop APP13 allows bounded noncolor resource IDs but refuses ICC unknown and malformed framing',async()=>{
 const jpg=await fixture('jpeg');for(const [id,data] of [[0x0404,Buffer.from('iptc')],[0x0425,Buffer.alloc(16)]])assert.equal(admitSourceColor(photoshopJPEG(jpg,id,data,Buffer.from('x'))).colorStatus,'assumed_srgb');
 for(const id of [0x040f,0x03ed,0xffff])refused(photoshopJPEG(jpg,id),'unsupported_photoshop_resource');
 const bad=photoshopJPEG(jpg,0x0404);bad[20]=0;assert.throws(()=>admitSourceColor(bad),/source_color_invalid/);
 const size=photoshopJPEG(jpg,0x0404);new DataView(size.buffer).setUint32(28,0xffffffff);assert.throws(()=>admitSourceColor(size),/source_color_invalid/);
 assert.throws(()=>admitSourceColor(photoshopJPEG(jpg,0x0425,Buffer.alloc(15))),/source_color_invalid/);
});
