-- Añejo HUB — default checklist templates (P7): seed opening/closing/prep/sanitation for the
-- kitchen team and vehicle/loadout/dropoff for the delivery (driver) team, so every location
-- has a starting checklist without owner setup. Ids are fixed so a re-run is a no-op
-- (INSERT OR IGNORE). Owners can edit/replace these later via the checklists table.
-- Apply: wrangler d1 execute anejo --remote --file=migrations/0040_checklist_seeds.sql

INSERT OR IGNORE INTO checklists (id, name, checklist_type, team, items, active, created_at, updated_at) VALUES
  ('chk_kitchen_opening', 'Kitchen Opening', 'opening', 'kitchen', '[{"key":"handwash_station","label":"Handwashing station stocked (soap, paper towels)","requires_photo":0,"requires_temp":0},{"key":"walkin_temp","label":"Walk-in cooler and reach-ins at safe temperature","requires_photo":0,"requires_temp":1},{"key":"surfaces_sanitized","label":"Prep surfaces sanitized before use","requires_photo":0,"requires_temp":0},{"key":"equipment_on","label":"Equipment powered on and warmed up","requires_photo":0,"requires_temp":0},{"key":"stock_checked","label":"Opening stock checked against par levels","requires_photo":0,"requires_temp":0}]', 1, 0, 0);

INSERT OR IGNORE INTO checklists (id, name, checklist_type, team, items, active, created_at, updated_at) VALUES
  ('chk_kitchen_closing', 'Kitchen Closing', 'closing', 'kitchen', '[{"key":"equipment_off","label":"Equipment powered off and cooled down","requires_photo":0,"requires_temp":0},{"key":"surfaces_cleaned","label":"All prep surfaces cleaned and sanitized","requires_photo":0,"requires_temp":0},{"key":"walkin_temp_close","label":"Walk-in cooler at safe temperature at close","requires_photo":0,"requires_temp":1},{"key":"trash_out","label":"Trash and recycling taken out","requires_photo":0,"requires_temp":0},{"key":"leftovers_labeled","label":"Leftover product labeled with date and stored","requires_photo":0,"requires_temp":0},{"key":"floors_swept","label":"Floors swept and mopped","requires_photo":0,"requires_temp":0}]', 1, 0, 0);

INSERT OR IGNORE INTO checklists (id, name, checklist_type, team, items, active, created_at, updated_at) VALUES
  ('chk_kitchen_prep', 'Kitchen Prep', 'prep', 'kitchen', '[{"key":"recipe_confirmed","label":"Today''s recipes/prep list confirmed","requires_photo":0,"requires_temp":0},{"key":"ingredients_staged","label":"Ingredients pulled and staged","requires_photo":0,"requires_temp":0},{"key":"portioning_checked","label":"Portion sizes checked against spec","requires_photo":0,"requires_temp":0},{"key":"allergen_check","label":"Allergen labels checked and applied","requires_photo":0,"requires_temp":0},{"key":"cook_temp_logged","label":"Cook temperatures logged for hot-held items","requires_photo":0,"requires_temp":1}]', 1, 0, 0);

INSERT OR IGNORE INTO checklists (id, name, checklist_type, team, items, active, created_at, updated_at) VALUES
  ('chk_kitchen_sanitation', 'Kitchen Sanitation', 'sanitation', 'kitchen', '[{"key":"handwash_supplies","label":"Handwashing supplies stocked","requires_photo":0,"requires_temp":0},{"key":"sanitizer_mixed","label":"Sanitizer solution mixed to correct concentration","requires_photo":0,"requires_temp":0},{"key":"dish_area_clean","label":"Dish/wash area clean and organized","requires_photo":0,"requires_temp":0},{"key":"food_contact_surfaces","label":"Food-contact surfaces sanitized between tasks","requires_photo":0,"requires_temp":0},{"key":"pest_check","label":"No signs of pests observed","requires_photo":0,"requires_temp":0}]', 1, 0, 0);

INSERT OR IGNORE INTO checklists (id, name, checklist_type, team, items, active, created_at, updated_at) VALUES
  ('chk_driver_vehicle', 'Driver Vehicle Check', 'vehicle', 'delivery', '[{"key":"vehicle_clean","label":"Vehicle interior clean and free of debris","requires_photo":0,"requires_temp":0},{"key":"fuel_level","label":"Fuel level checked and adequate for route","requires_photo":0,"requires_temp":0},{"key":"cooler_temp","label":"Delivery coolers at safe temperature","requires_photo":0,"requires_temp":1},{"key":"tires_lights","label":"Tires and lights visually checked","requires_photo":0,"requires_temp":0},{"key":"docs_onboard","label":"Route sheet and delivery docs onboard","requires_photo":0,"requires_temp":0}]', 1, 0, 0);

INSERT OR IGNORE INTO checklists (id, name, checklist_type, team, items, active, created_at, updated_at) VALUES
  ('chk_driver_loadout', 'Driver Loadout', 'loadout', 'delivery', '[{"key":"order_count_matches","label":"Order count matches route manifest","requires_photo":0,"requires_temp":0},{"key":"bags_sealed","label":"Bags and containers sealed and labeled","requires_photo":0,"requires_temp":0},{"key":"cooler_packed","label":"Cold items packed in coolers with ice packs","requires_photo":0,"requires_temp":1},{"key":"fragile_secured","label":"Fragile and liquid items secured upright","requires_photo":0,"requires_temp":0},{"key":"photo_loadout","label":"Photo of loaded vehicle taken","requires_photo":1,"requires_temp":0}]', 1, 0, 0);

INSERT OR IGNORE INTO checklists (id, name, checklist_type, team, items, active, created_at, updated_at) VALUES
  ('chk_driver_dropoff', 'Driver Drop-off', 'dropoff', 'delivery', '[{"key":"address_confirmed","label":"Delivery address confirmed against order","requires_photo":0,"requires_temp":0},{"key":"handoff_or_photo","label":"Handed to recipient or proof photo taken","requires_photo":1,"requires_temp":0},{"key":"temp_ok_at_dropoff","label":"Product still within safe temperature at drop-off","requires_photo":0,"requires_temp":1},{"key":"signature_captured","label":"Signature captured when required","requires_photo":0,"requires_temp":0},{"key":"app_marked_complete","label":"Delivery marked complete in the app","requires_photo":0,"requires_temp":0}]', 1, 0, 0);

