-- Partial BJ order9538: three readable lines; receipt total is not visible. No historical stock assertion.
INSERT OR IGNORE INTO inventory_purchase_costs(id,supplier_id,purchased_on,receipt_reference,line_ordinal,item_name,purchased_packs,pack_quantity,pack_unit,paid_line_cents,source_path,source_type) VALUES('bjs_20261001_9538_1','supplier_bjs','2026-10-01','9538','1','Wellsley Farms Idaho Potatoes','4','10','each','1260','/Users/aiagent/Downloads/Screenshot 2026-10-05 at 3.41.47 PM.png','paid_receipt');
INSERT OR IGNORE INTO inventory_items(id,name,unit,on_hand,par_level,vendor_id,supplier_id,active,unit_cost_cents,count_quantity,total_weight_grams,counted_at,created_at,updated_at) VALUES('inv_bjs_20261001_9538_potatoes','Wellsley Farms Idaho Potatoes — BJ Oct1 receipt','each',NULL,'0',NULL,'supplier_bjs','1',NULL,NULL,NULL,NULL,CAST(strftime('%s','now') AS INTEGER)*1000,CAST(strftime('%s','now') AS INTEGER)*1000);
INSERT OR IGNORE INTO inventory_purchase_costs(id,supplier_id,purchased_on,receipt_reference,line_ordinal,item_name,purchased_packs,pack_quantity,pack_unit,paid_line_cents,source_path,source_type) VALUES('bjs_20261001_9538_2','supplier_bjs','2026-10-01','9538','2','Wellsley Farms Canola Oil','1',NULL,NULL,'1299','/Users/aiagent/Downloads/Screenshot 2026-10-05 at 3.41.47 PM.png','paid_receipt');
INSERT OR IGNORE INTO inventory_items(id,name,unit,on_hand,par_level,vendor_id,supplier_id,active,unit_cost_cents,count_quantity,total_weight_grams,counted_at,created_at,updated_at) VALUES('inv_bjs_20261001_9538_oil','Wellsley Farms Canola Oil — BJ Oct1 receipt','pack',NULL,'0',NULL,'supplier_bjs','1',NULL,NULL,NULL,NULL,CAST(strftime('%s','now') AS INTEGER)*1000,CAST(strftime('%s','now') AS INTEGER)*1000);
INSERT OR IGNORE INTO inventory_purchase_costs(id,supplier_id,purchased_on,receipt_reference,line_ordinal,item_name,purchased_packs,pack_quantity,pack_unit,paid_line_cents,source_path,source_type) VALUES('bjs_20261001_9538_3','supplier_bjs','2026-10-01','9538','3','Wellsley Farms Sour Cream','1','32','oz','329','/Users/aiagent/Downloads/Screenshot 2026-10-05 at 3.41.47 PM.png','paid_receipt');
INSERT OR IGNORE INTO inventory_items(id,name,unit,on_hand,par_level,vendor_id,supplier_id,active,unit_cost_cents,count_quantity,total_weight_grams,counted_at,created_at,updated_at) VALUES('inv_bjs_20261001_9538_sourcream','Wellsley Farms Sour Cream — BJ Oct1 receipt','oz',NULL,'0',NULL,'supplier_bjs','1',NULL,NULL,NULL,NULL,CAST(strftime('%s','now') AS INTEGER)*1000,CAST(strftime('%s','now') AS INTEGER)*1000);
INSERT OR IGNORE INTO inventory_changes(id,item_id,action,actor_id,before_json,after_json,created_at,push_status) SELECT 'ich_receipt_'||id,id,'historical_receipt',NULL,NULL,json_object('name',name,'supplier_id',supplier_id,'on_hand',on_hand,'counted_at',counted_at),CAST(strftime('%s','now') AS INTEGER)*1000,'not_attempted' FROM inventory_items WHERE id LIKE 'inv_bjs_20261001_9538_%';
UPDATE inventory_items SET last_change_id='ich_receipt_'||id WHERE id LIKE 'inv_bjs_20261001_9538_%' AND last_change_id IS NULL;
