-- Existing receipt11137; exact costs only, no new stock.
INSERT OR IGNORE INTO inventory_purchase_costs(id,supplier_id,purchased_on,receipt_reference,line_ordinal,item_name,purchased_packs,pack_quantity,pack_unit,paid_line_cents,source_path,source_type) VALUES('rd_20261005_11137_1','supplier_restaurant_depot','2026-10-05','11137','1','ECOBOX #8 KRAFT','1','50','each','839','/Users/aiagent/Downloads/IMG_1734.HEIC','paid_receipt');
INSERT OR IGNORE INTO inventory_purchase_costs(id,supplier_id,purchased_on,receipt_reference,line_ordinal,item_name,purchased_packs,pack_quantity,pack_unit,paid_line_cents,source_path,source_type) VALUES('rd_20261005_11137_2','supplier_restaurant_depot','2026-10-05','11137','2','ECOBOX #1 WHITE','1','50','each','944','/Users/aiagent/Downloads/IMG_1734.HEIC','paid_receipt');
INSERT OR IGNORE INTO inventory_purchase_costs(id,supplier_id,purchased_on,receipt_reference,line_ordinal,item_name,purchased_packs,pack_quantity,pack_unit,paid_line_cents,source_path,source_type) VALUES('rd_20261005_11137_3','supplier_restaurant_depot','2026-10-05','11137','3','CUP SFL 1Z SUNSET','1','250','each','261','/Users/aiagent/Downloads/IMG_1734.HEIC','paid_receipt');
INSERT OR IGNORE INTO inventory_purchase_costs(id,supplier_id,purchased_on,receipt_reference,line_ordinal,item_name,purchased_packs,pack_quantity,pack_unit,paid_line_cents,source_path,source_type) VALUES('rd_20261005_11137_4','supplier_restaurant_depot','2026-10-05','11137','4','LID SFL .75-1Z','1','125','each','156','/Users/aiagent/Downloads/IMG_1734.HEIC','paid_receipt');
INSERT OR IGNORE INTO inventory_purchase_costs(id,supplier_id,purchased_on,receipt_reference,line_ordinal,item_name,purchased_packs,pack_quantity,pack_unit,paid_line_cents,source_path,source_type) VALUES('rd_20261005_11137_5','supplier_restaurant_depot','2026-10-05','11137','5','LID SFL .75-1Z','1','125','each','156','/Users/aiagent/Downloads/IMG_1734.HEIC','paid_receipt');
INSERT OR IGNORE INTO inventory_purchase_costs(id,supplier_id,purchased_on,receipt_reference,line_ordinal,item_name,purchased_packs,pack_quantity,pack_unit,paid_line_cents,source_path,source_type) VALUES('rd_20261005_11137_6','supplier_restaurant_depot','2026-10-05','11137','6','LID PL 1.5-2.0','1','125','each','215','/Users/aiagent/Downloads/IMG_1734.HEIC','paid_receipt');
INSERT OR IGNORE INTO inventory_purchase_costs(id,supplier_id,purchased_on,receipt_reference,line_ordinal,item_name,purchased_packs,pack_quantity,pack_unit,paid_line_cents,source_path,source_type) VALUES('rd_20261005_11137_7','supplier_restaurant_depot','2026-10-05','11137','7','LID PL 1.5-2.0','1','125','each','215','/Users/aiagent/Downloads/IMG_1734.HEIC','paid_receipt');
INSERT OR IGNORE INTO inventory_purchase_costs(id,supplier_id,purchased_on,receipt_reference,line_ordinal,item_name,purchased_packs,pack_quantity,pack_unit,paid_line_cents,source_path,source_type) VALUES('rd_20261005_11137_8','supplier_restaurant_depot','2026-10-05','11137','8','CUP SFL BLK 2Z','1','250','each','362','/Users/aiagent/Downloads/IMG_1734.HEIC','paid_receipt');
INSERT OR IGNORE INTO inventory_purchase_costs(id,supplier_id,purchased_on,receipt_reference,line_ordinal,item_name,purchased_packs,pack_quantity,pack_unit,paid_line_cents,source_path,source_type) VALUES('rd_20261005_11137_9','supplier_restaurant_depot','2026-10-05','11137','9','SOUR CREAM DAISY','1','5','lb','908','/Users/aiagent/Downloads/IMG_1734.HEIC','paid_receipt');
INSERT OR IGNORE INTO inventory_purchase_costs(id,supplier_id,purchased_on,receipt_reference,line_ordinal,item_name,purchased_packs,pack_quantity,pack_unit,paid_line_cents,source_path,source_type) VALUES('rd_20261005_11137_10','supplier_restaurant_depot','2026-10-05','11137','10','PROD ORG HERB MIX','1','2','lb','1234','/Users/aiagent/Downloads/IMG_1734.HEIC','paid_receipt');
INSERT OR IGNORE INTO inventory_purchase_costs(id,supplier_id,purchased_on,receipt_reference,line_ordinal,item_name,purchased_packs,pack_quantity,pack_unit,paid_line_cents,source_path,source_type) VALUES('rd_20261005_11137_11','supplier_restaurant_depot','2026-10-05','11137','11','PROD PEPP RED BAG','1','5','lb','1118','/Users/aiagent/Downloads/IMG_1734.HEIC','paid_receipt');
INSERT OR IGNORE INTO inventory_purchase_costs(id,supplier_id,purchased_on,receipt_reference,line_ordinal,item_name,purchased_packs,pack_quantity,pack_unit,paid_line_cents,source_path,source_type) VALUES('rd_20261005_11137_12','supplier_restaurant_depot','2026-10-05','11137','12','PROD LETT TOSSED','1','5','lb','971','/Users/aiagent/Downloads/IMG_1734.HEIC','paid_receipt');
INSERT OR IGNORE INTO inventory_purchase_costs(id,supplier_id,purchased_on,receipt_reference,line_ordinal,item_name,purchased_packs,pack_quantity,pack_unit,paid_line_cents,source_path,source_type) VALUES('rd_20261005_11137_13','supplier_restaurant_depot','2026-10-05','11137','13','BF GROUND 80/20','1','9.73','raw lb','4536','/Users/aiagent/Downloads/IMG_1734.HEIC','paid_receipt');
INSERT OR IGNORE INTO inventory_purchase_costs(id,supplier_id,purchased_on,receipt_reference,line_ordinal,item_name,purchased_packs,pack_quantity,pack_unit,paid_line_cents,source_path,source_type) VALUES('rd_20261005_11137_14','supplier_restaurant_depot','2026-10-05','11137','14','PROD POTATO UTIL','1','70','each','2504','/Users/aiagent/Downloads/IMG_1734.HEIC','paid_receipt');
INSERT OR IGNORE INTO inventory_changes(id,item_id,action,actor_id,before_json,after_json,created_at,push_status) SELECT 'ich_supplier_'||id,id,'supplier_link',NULL,json_object('supplier_id',supplier_id,'on_hand',on_hand,'counted_at',counted_at),json_object('supplier_id','supplier_restaurant_depot','on_hand',on_hand,'counted_at',counted_at),CAST(strftime('%s','now') AS INTEGER)*1000,'not_attempted' FROM inventory_items WHERE id LIKE 'inv_rd_20261005_%' AND supplier_id IS NULL;
UPDATE inventory_items SET supplier_id='supplier_restaurant_depot',revision=revision+1,last_change_id='ich_supplier_'||id WHERE id LIKE 'inv_rd_20261005_%' AND supplier_id IS NULL;
