import {test} from 'node:test';
import assert from 'node:assert/strict';
import {ownerEnv,OWNER_COOKIE} from '../helpers/sqlite-d1.js';
import {onRequestGet,onRequestPost} from '../../functions/api/hub/owner/google-reviews.js';
import {validateReviewDraft} from '../../functions/_lib/google_review_drafts.js';
const body=()=>({op:'create',request_id:'local-test-request-01',review_text:'Example review for an internal fixture.',proposed_reply:'Thank you for your feedback.',rating:4});
const req=(b,cookie=OWNER_COOKIE)=>new Request('https://anejo.test/api/hub/owner/google-reviews',{method:b?'POST':'GET',headers:{Cookie:cookie},...(b?{body:JSON.stringify(b)}:{})});
async function post(env,b){return onRequestPost({env,request:req(b)});}
test('disconnected adapter saves only manual draft and retries do not duplicate',async()=>{const env=ownerEnv();const r=await post(env,body());assert.equal(r.status,200);const d=await r.json();assert.equal(d.connected,false);assert.equal(d.reply_publish,'unavailable');assert.equal(d.draft.source_kind,'manual_unverified');const again=await(await post(env,body())).json();assert.equal(d.draft.id,again.draft.id);const list=await(await onRequestGet({env,request:req()})).json();assert.equal(list.drafts.length,1);assert.equal(list.list_scope,'latest_100_local_drafts');});
test('stale edit and request reuse conflict preserve previous reply',async()=>{const env=ownerEnv();const {draft}=await(await post(env,body())).json();assert.equal((await post(env,{...body(),proposed_reply:'Changed'})).status,409);const edit={...body(),op:'edit',id:draft.id,version:1};delete edit.request_id;edit.proposed_reply='Revised draft';assert.equal((await post(env,edit)).status,200);assert.equal((await post(env,edit)).status,409);assert.equal((await post(env,{op:'dismiss',id:draft.id,version:2})).status,200);assert.equal((await post(env,{...edit,version:3})).status,409);});
test('unsupported external actions and malformed input are rejected',async()=>{const env=ownerEnv();for(const b of [{...body(),op:'send'},{...body(),op:'sync'},{...body(),approved:true},{...body(),rating:6},{...body(),source_url:'https://evil.example/maps'},{...body(),proposed_reply:'x'.repeat(3001)}])assert.equal((await post(env,b)).status,400);assert.ok(validateReviewDraft({...body(),source_url:'https://maps.app.goo.gl/example'}).value);});
test('storage unavailable is explicit, never an empty live inbox',async()=>{const env=ownerEnv();env.DB.sqlite.exec('DROP TABLE google_review_drafts');const r=await onRequestGet({env,request:req()});assert.equal(r.status,503);const d=await r.json();assert.equal(d.storage,'unavailable');assert.equal(d.drafts,undefined);assert.equal(d.connected,false);});
test('current roles gate reads and writes',async()=>{const env=ownerEnv();for(const cookie of ['','anejo_sess=tok-kitchen']){const r=await onRequestGet({env,request:req(null,cookie)});assert.ok([401,403].includes(r.status));}env.DB.sqlite.exec("UPDATE staff SET role='marketing' WHERE id='stf_owner'");assert.equal((await post(env,body())).status,200);env.DB.sqlite.exec("UPDATE staff SET active=0 WHERE id='stf_owner'");assert.equal((await post(env,body())).status,401);});
