import {test} from 'node:test';import assert from 'node:assert/strict';
import {ownerEnv,OWNER_COOKIE} from '../helpers/sqlite-d1.js';
import {sendAnaDraft} from '../../functions/_lib/instagram_reply_attempt.js';
import {onRequestPost as inboxPost} from '../../functions/api/hub/owner/social-inbox.js';
function setup(kind='dm'){const env=ownerEnv(),t=Date.now();env.DB.sqlite.prepare("INSERT INTO threads(id,audience,external_id,last_inbound_at,status,created_at,updated_at) VALUES ('t','instagram','customer',?,'open',?,?)").run(t,t,t);env.DB.sqlite.prepare("INSERT INTO messages(id,thread_id,direction,channel,sender_id,sender_role,body,ai_drafted,created_at) VALUES ('in','t','inbound','instagram','customer','customer','Question',0,?)").run(t);env.DB.sqlite.prepare("INSERT INTO messages(id,thread_id,direction,channel,sender_id,sender_role,body,ai_drafted,created_at,ref_id,reply_to_message_id) VALUES ('out','t','outbound','instagram','ana','ana_draft','Exact reply',1,?,?,'in')").run(t+1,kind==='comment'?'comment1':null);return env;}
const args={messageId:'out',threadId:'t',expectedBody:'Exact reply',initiatedBy:'stf_owner'};
const manual=(env,op,extra={})=>inboxPost({env,request:new Request('https://anejo.test/api/hub/owner/social-inbox',{method:'POST',headers:{cookie:OWNER_COOKIE},body:JSON.stringify({op,message_id:'out',thread_id:'t',...extra})})});
test('manual/automatic overlap claims exact draft once and replay reports historical provider receipt',async()=>{const env=setup();let calls=0,release;const gate=new Promise(r=>{release=r;});const provider=async input=>{calls++;assert.equal(input.text,'Exact reply');assert.equal(input.recipientId,'customer');await gate;return {ok:true,body:{message_id:'provider1'}};};const first=sendAnaDraft(env,args,provider);while(!calls)await new Promise(r=>setTimeout(r,1));const overlap=await sendAnaDraft(env,{...args,initiatedBy:'ana_auto'},provider);assert.equal(overlap.state,'claimed');assert.equal(overlap.sent,false);assert.equal((await manual(env,'edit',{body:'Changed'})).status,409);assert.equal((await manual(env,'dismiss')).status,409);release();const sent=await first;assert.equal(sent.sent,true);assert.equal(sent.replayed,false);const retry=await sendAnaDraft(env,args,provider);assert.equal(calls,1);assert.equal(retry.replayed,true);assert.equal(retry.provider_message_id,'provider1');assert.equal(retry.sent_at,sent.sent_at);assert.equal(env.DB.one("SELECT body FROM instagram_reply_attempts").body,'Exact reply');});
test('different drafts for same inbound trigger cannot send twice, including comments',async()=>{for(const kind of ['dm','comment']){const env=setup(kind);env.DB.exec("INSERT INTO messages(id,thread_id,direction,channel,sender_id,sender_role,body,ai_drafted,created_at,ref_id,reply_to_message_id) SELECT 'duplicate',thread_id,direction,channel,sender_id,sender_role,'Other draft',ai_drafted,created_at,ref_id,reply_to_message_id FROM messages WHERE id='out'");let calls=0;const provider=async()=>{calls++;return {ok:true,body:{id:'provider'}};};const results=await Promise.all([sendAnaDraft(env,args,provider),sendAnaDraft(env,{...args,messageId:'duplicate',expectedBody:'Other draft'},provider)]);assert.equal(calls,1);assert.equal(env.DB.one('SELECT COUNT(*) n FROM instagram_reply_attempts').n,1);assert.ok(results.some(r=>r.replayed));}});
test('provider success followed by DB failure remains unknown and is never automatically resent',async()=>{const env=setup();let calls=0;const batch=env.DB.batch;env.DB.batch=async()=>{throw Error('DB failure');};const provider=async()=>{calls++;return {ok:true,body:{message_id:'delivered-id'}};};const result=await sendAnaDraft(env,args,provider);assert.equal(result.state,'unknown');assert.equal(result.sent,false);env.DB.batch=batch;const retry=await sendAnaDraft(env,args,provider);assert.equal(calls,1);assert.equal(retry.state,'unknown');assert.equal(retry.provider_message_id,'delivered-id');assert.equal(env.DB.one("SELECT sent_at FROM messages WHERE id='out'").sent_at,null);});
test('ambiguous transport or success without provider ID cannot claim sent or retry',async()=>{for(const response of [{ok:false,delivery_uncertain:true,error:'SECRET'},{ok:true,body:{}}]){const env=setup();let calls=0;const provider=async()=>{calls++;return response;};assert.equal((await sendAnaDraft(env,args,provider)).state,'unknown');assert.equal((await sendAnaDraft(env,args,provider)).state,'unknown');assert.equal(calls,1);assert.ok(!JSON.stringify(env.DB.one('SELECT * FROM instagram_reply_attempts')).includes('SECRET'));}});
test('legacy DM ambiguous trigger or stale recipient fails closed before provider',async()=>{for(const mode of ['ambiguous','recipient','missing']){const env=setup();env.DB.exec("UPDATE messages SET reply_to_message_id=NULL WHERE id='out'");if(mode==='ambiguous')env.DB.exec("INSERT INTO messages(id,thread_id,direction,channel,sender_id,sender_role,body,created_at) SELECT 'tie',thread_id,direction,channel,sender_id,sender_role,body,created_at FROM messages WHERE id='in'");if(mode==='recipient')env.DB.exec("UPDATE threads SET external_id='changed'");if(mode==='missing')env.DB.exec("DELETE FROM messages WHERE id='in'");let calls=0;const result=await sendAnaDraft(env,args,async()=>{calls++;});assert.equal(result.error,'inbound_trigger_unavailable');assert.equal(calls,0);}});
