import {test} from 'node:test';
import assert from 'node:assert/strict';
import {ownerEnv,OWNER_COOKIE} from '../helpers/sqlite-d1.js';
import {onRequestPost as save} from '../../functions/api/hub/owner/marketing-branded-save.js';
import {onRequestGet as getSource} from '../../functions/api/hub/owner/marketing-original-source.js';
import {sha256} from '../../functions/_lib/marketing_render_receipt.js';
import {resolvePreEditorialSource,recoveryDeclaration} from '../../functions/_lib/marketing_original_source.js';
const original='studio/original_photo.jpg',jpeg=new Uint8Array([255,216,255,192,0,11,8,0,10,0,10,1,1,17,0,255,218,0,2,0,255,217]);
const call=(env,body)=>save({env,request:new Request('https://anejo.test/api/hub/owner/marketing-branded-save',{method:'POST',headers:{cookie:OWNER_COOKIE,'content-type':'application/json'},body:JSON.stringify(body)})});
async function fixture(depth=2){const env=ownerEnv(),objects=new Map([[original,jpeg.slice()]]),metadata=new Map([[original,{ai_enhanced:'true',enhancement_method:'photographic'}]]);env.MEDIA={get:async key=>objects.has(key)?{size:objects.get(key).length,customMetadata:metadata.get(key)||{},arrayBuffer:async()=>objects.get(key).slice().buffer}:null,put:async(key,bytes,options)=>{objects.set(key,new Uint8Array(bytes));metadata.set(key,options.customMetadata);}};
 env.DB.exec("INSERT INTO social_posts(id,status,caption,public_token,created_at,updated_at) VALUES ('p','draft','caption','pt',1,1);INSERT INTO social_post_media(id,post_id,seq,media_key,public_token,created_at) VALUES ('m','p',0,'studio/original_photo.jpg','mt',1)");
 let key=original;const body={post_id:'p',media_id:'m',source_sha256:await sha256(jpeg),data_url:'data:image/jpeg;base64,'+Buffer.from(jpeg).toString('base64'),declaration:{renderer_version:'test',template_id:'reposado',options:{},layout:{}}};
 for(let i=1;i<=depth;i++){const response=await(await call(env,{...body,request_id:`12345678-1234-4123-8123-${String(i).padStart(12,'0')}`,source_key:key})).json();assert.equal(response.ok,true);key=response.media_key;}
 return {env,objects,metadata,key,body};}
const get=(f,cookie=OWNER_COOKIE,key=f.key)=>getSource({env:f.env,request:new Request('https://anejo.test/api/hub/owner/marketing-original-source?post_id=p&media_id=m&current_key='+encodeURIComponent(key),{headers:{cookie}})});
test('verified editorial chain resolves preserved photographic source without touching objects or slide',async()=>{const f=await fixture();const before=f.objects.size;const response=await get(f),r=await response.json();assert.equal(response.status,200);assert.equal(r.source_key,original);assert.equal(r.source_sha256,await sha256(jpeg));assert.equal(r.recovery.depth,2);assert.equal(r.visual_review_required,true);assert.equal(f.objects.size,before);assert.equal(f.env.DB.one('SELECT media_key FROM social_post_media').media_key,f.key);assert.equal(f.metadata.get(original).ai_enhanced,'true');});
test('recovered render atomically replaces current slide, preserves source AI history and retry identity',async()=>{const f=await fixture(),r=await(await get(f)).json();const body={...f.body,request_id:'12345678-1234-4123-8123-000000000099',source_key:r.source_key,declaration:{...f.body.declaration,options:{original_source_recovery:r.recovery}}};f.env.DB.exec("UPDATE social_posts SET status='scheduled',scheduled_at=99,audit_score=100,audit_status='passed'");const response=await(await call(f.env,body)).json();assert.equal(response.attached,true);assert.equal(f.env.DB.one('SELECT media_key FROM social_post_media').media_key,response.media_key);assert.equal(f.env.DB.one('SELECT COUNT(*) n FROM social_post_media').n,1);const post=f.env.DB.one('SELECT status,scheduled_at,audit_score FROM social_posts');assert.equal(post.status,'draft');assert.equal(post.scheduled_at,null);assert.equal(post.audit_score,null);assert.equal(f.metadata.get(response.media_key).source_key,original);assert.equal(f.metadata.get(response.media_key).ai_enhanced,'true');assert.deepEqual(f.objects.get(original),jpeg);assert.equal((await(await call(f.env,body)).json()).receipt_id,response.receipt_id);});
test('roles and stale slide selection cannot read recovery source',async()=>{const f=await fixture();assert.equal((await get(f,'anejo_sess=tok-kitchen')).status,403);assert.equal((await get(f,OWNER_COOKIE,original)).status,409);});
for(const mode of ['bytes','metadata','receipt','pending'])test('changed '+mode+' blocks lineage recovery without mutation',async()=>{const f=await fixture();if(mode==='bytes')f.objects.get(f.key)[3]=1;if(mode==='metadata')f.metadata.set(f.key,{source_key:original,enhancement_method:'photographic'});if(mode==='receipt')f.env.DB.sqlite.prepare('DELETE FROM marketing_render_receipts WHERE output_key=?').run(f.key);if(mode==='pending')f.env.DB.sqlite.prepare("UPDATE marketing_render_receipts SET state='pending' WHERE output_key=?").run(f.key);assert.equal((await get(f)).status,409);assert.equal(f.env.DB.one('SELECT media_key FROM social_post_media').media_key,f.key);});
test('missing preserved source and arbitrary metadata pointers are not evidence',async()=>{const f=await fixture();f.objects.delete(original);assert.equal((await get(f)).status,409);const plain=await fixture(0);plain.metadata.set(original,{source_key:'studio/claimed.jpg',enhancement_method:'editorial_overlay'});await assert.rejects(resolvePreEditorialSource(plain.env,original),/unverified/);});
test('cycles and more than eight recorded overlays fail closed',async()=>{const f=await fixture(1);f.env.DB.sqlite.prepare('UPDATE marketing_render_receipts SET source_key=?').run(f.key);f.metadata.get(f.key).source_key=f.key;await assert.rejects(resolvePreEditorialSource(f.env,f.key),/cycle/);const deep=await fixture(9);await assert.rejects(resolvePreEditorialSource(deep.env,deep.key),/limit/);});
test('forged recovery declaration cannot swap an arbitrary source',async()=>{const f=await fixture(),source=await resolvePreEditorialSource(f.env,f.key),body={...f.body,source_key:original,request_id:'12345678-1234-4123-8123-000000000099',declaration:{...f.body.declaration,options:{original_source_recovery:{...recoveryDeclaration(source),depth:1}}}};assert.equal((await call(f.env,body)).status,409);assert.equal(f.env.DB.one('SELECT media_key FROM social_post_media').media_key,f.key);});
test('slide race during write leaves artifact unattached and cannot overwrite newer selection',async()=>{const f=await fixture(),source=await resolvePreEditorialSource(f.env,f.key),put=f.env.MEDIA.put;f.env.MEDIA.put=async(...args)=>{await put(...args);f.env.DB.sqlite.prepare('UPDATE social_post_media SET media_key=?').run('studio/new-selection.jpg');};const r=await call(f.env,{...f.body,source_key:original,request_id:'12345678-1234-4123-8123-000000000099',declaration:{...f.body.declaration,options:{original_source_recovery:recoveryDeclaration(source)}}});assert.equal(r.status,409);assert.equal((await r.json()).attached,false);assert.equal(f.env.DB.one('SELECT media_key FROM social_post_media').media_key,'studio/new-selection.jpg');});
for(const state of ['missing','mismatched'])test('metadata diagnostic reports bounded state at failing chain link: '+state,async()=>{const f=await fixture();const parent=f.metadata.get(f.key).source_key;f.metadata.set(parent,state==='missing'?{private_note:'must not leak'}:{enhancement_method:'unexpected-private-value',source_key:'studio/wrong.jpg',private_note:'must not leak'});const response=await get(f),r=await response.json();assert.equal(response.status,409);assert.equal(r.error,'editorial_history_metadata_changed');assert.deepEqual(r.history_diagnostic,{key:parent,depth:1,method_state:state,parent_state:state});assert.ok(!JSON.stringify(r).includes('private'));assert.ok(!JSON.stringify(r).includes('wrong.jpg'));assert.equal(f.env.DB.one('SELECT media_key FROM social_post_media').media_key,f.key);});
