import {buildSpine,renderSpine} from '../../functions/_lib/team_lead.js';
import {test} from 'node:test';import assert from 'node:assert/strict';
import {onRequestPost} from '../../functions/api/hub/owner/operator-campaign-promote.js';
import {currentPromotionAuthority,proposalDigest} from '../../functions/_lib/operator_campaign_promotion.js';
import {ownerEnv,OWNER_COOKIE} from '../helpers/sqlite-d1.js';
const preview_id='ocp_'+'a'.repeat(64),request_id='12345678-1234-4123-8123-123456789abc';
async function setup(){const env=ownerEnv();const authority=await currentPromotionAuthority(env);assert.equal(authority.ok,true);const proposal={title:'Catering plan',objective:'Review only',audience:'Local hosts',angle:'Event food',channels:['instagram'],product_ids:[authority.available_product_ids[0]],cadence:'Draft only',success_metric:'Quote inquiries',assets:[],assumptions:['Date unknown'],questions:['Which city?']};const p=JSON.stringify(proposal),sources=JSON.stringify({input_context:{components:authority.components}});env.DB.sqlite.prepare("INSERT INTO operator_campaign_previews(id,owner_id,request_id,idea_id,topic,topic_sha256,state,proposal_json,source_receipts_json,created_at,updated_at) VALUES (?,'stf_owner',?,'idea','Original owner words',?,'succeeded',?,?,1,1)").run(preview_id,request_id,await proposalDigest('Original owner words'),p,sources);return {env,proposal,body:{request_id,preview_id,expected_proposal_sha256:await proposalDigest(p),acknowledge_open_questions:true}};}
const call=(env,body,cookie=OWNER_COOKIE)=>onRequestPost({env,request:new Request('https://anejocateringco.com/api/hub/owner/operator-campaign-promote',{method:'POST',headers:{cookie,'content-type':'application/json'},body:JSON.stringify(body)})});
test('concurrent reviewed promotion makes one existing-engine brief and preserves immutable unknowns',async()=>{const {env,body,proposal}=await setup();const baseline=env.DB.one('SELECT COUNT(*) n FROM team_briefs').n;const original=globalThis.fetch;globalThis.fetch=()=>{throw Error('No inference');};try{const results=await Promise.all([call(env,body),call(env,{...body,request_id:'22345678-1234-4123-8123-123456789abc'})]);const replies=await Promise.all(results.map(r=>r.json()));assert.ok(replies.every(r=>r.promoted),JSON.stringify(replies));assert.equal(replies[0].brief_id,replies[1].brief_id);assert.equal(env.DB.one('SELECT COUNT(*) n FROM team_briefs').n,baseline+1);const receipt=env.DB.one('SELECT * FROM operator_campaign_promotions');assert.deepEqual(JSON.parse(receipt.proposal_json).questions,proposal.questions);assert.deepEqual(JSON.parse(receipt.proposal_json).assumptions,proposal.assumptions);assert.equal(receipt.review_scope,'team_planning_only');const prompt=renderSpine(await buildSpine(env));assert.ok(prompt.includes('Date unknown'));assert.ok(prompt.includes('Which city?'));assert.ok(prompt.includes(proposal.product_ids[0]));assert.equal(env.DB.one('SELECT topic FROM operator_campaign_previews').topic,'Original owner words');assert.equal(env.DB.one('SELECT COUNT(*) n FROM social_posts').n,0);}finally{globalThis.fetch=original;}});
test('changed source, missing evidence and unavailable reads cannot activate',async()=>{for(const kind of ['price','brand','receipt','stock','outage']){const {env,body,proposal}=await setup();if(kind==='price')env.DB.sqlite.prepare('UPDATE menu_items SET price_cents=price_cents+1 WHERE id=?').run(proposal.product_ids[0]);if(kind==='brand')env.DB.exec("INSERT INTO docs(id,title,body,doc_type,active,created_at,updated_at) VALUES ('b','Brand','Changed','brand',1,1,1)");if(kind==='stock')env.DB.sqlite.prepare('UPDATE menu_items SET stock_count=0 WHERE id=?').run(proposal.product_ids[0]);if(kind==='receipt')env.DB.exec("UPDATE operator_campaign_previews SET source_receipts_json='{}'");if(kind==='outage')env.DB.exec('DROP TABLE training_rules');const response=await call(env,body);assert.ok([409,503].includes(response.status));assert.equal(env.DB.one('SELECT COUNT(*) n FROM operator_campaign_promotions').n,0);}});
test('authority mutation after reads is blocked by raw-value CAS even without timestamp change',async()=>{const {env,body,proposal}=await setup();const batch=env.DB.batch;env.DB.batch=async statements=>{env.DB.sqlite.prepare('UPDATE menu_items SET price_cents=price_cents+1 WHERE id=?').run(proposal.product_ids[0]);return batch(statements);};const response=await call(env,body);assert.equal(response.status,409);assert.equal(env.DB.one('SELECT COUNT(*) n FROM operator_campaign_promotions').n,0);});
test('transaction rollback leaves no brief and retry after readback outage does not duplicate',async()=>{const {env,body}=await setup();const initial=env.DB.one('SELECT COUNT(*) n FROM team_briefs').n;env.DB.exec("CREATE TRIGGER reject_promotion BEFORE INSERT ON operator_campaign_promotions BEGIN SELECT RAISE(ABORT,'fail'); END");assert.equal((await call(env,body)).status,503);assert.equal(env.DB.one('SELECT COUNT(*) n FROM team_briefs').n,initial);env.DB.exec('DROP TRIGGER reject_promotion');assert.equal((await (await call(env,body)).json()).promoted,true);assert.equal((await (await call(env,body)).json()).promoted,true);assert.equal(env.DB.one('SELECT COUNT(*) n FROM team_briefs').n,initial+1);});
test('owner-only, explicit review and exact proposal hash required',async()=>{const {env,body}=await setup();assert.equal((await call(env,body,'anejo_sess=tok-marketing')).status,403);assert.equal((await call(env,{...body,acknowledge_open_questions:false})).status,400);assert.equal((await call(env,{...body,expected_proposal_sha256:'0'.repeat(64)})).status,409);assert.equal((await call(env,{...body,approved:true})).status,400);assert.equal(env.DB.one('SELECT COUNT(*) n FROM operator_campaign_promotions').n,0);});
test('preview reload separates historical promotion receipt from archived or edited team brief',async()=>{const {onRequestGet}=await import('../../functions/api/hub/owner/operator-campaign-preview.js');const {env,body}=await setup();const get=()=>onRequestGet({env,request:new Request('https://anejocateringco.com/api/hub/owner/operator-campaign-preview?id='+preview_id,{headers:{cookie:OWNER_COOKIE}})});let preview=(await (await get()).json()).preview;assert.equal(preview.promotion_status,'not_recorded');assert.equal(preview.proposal_sha256,body.expected_proposal_sha256);const result=await (await call(env,body)).json();preview=(await (await get()).json()).preview;assert.equal(preview.promotion_status,'recorded');assert.equal(preview.promotion.brief_matches_reviewed_proposal,true);env.DB.sqlite.prepare("UPDATE team_briefs SET status='archived',objective='Edited' WHERE id=?").run(result.brief_id);preview=(await (await get()).json()).preview;assert.equal(preview.promotion.brief_status,'archived');assert.equal(preview.promotion.brief_matches_reviewed_proposal,false);env.DB.exec('DROP TABLE operator_campaign_promotions');preview=(await (await get()).json()).preview;assert.equal(preview.promotion_status,'unavailable');});

test('reviewed1084character direction survives exact promotion and existing Lead consumer',async()=>{
 const {env,body,proposal}=await setup();proposal.angle='Creative direction. '.repeat(60).slice(0,1084);const exact=JSON.stringify(proposal);env.DB.sqlite.prepare('UPDATE operator_campaign_previews SET proposal_json=? WHERE id=?').run(exact,preview_id);body.expected_proposal_sha256=await proposalDigest(exact);
 const r=await(await call(env,body)).json();assert.equal(r.promoted,true,JSON.stringify(r));assert.equal(env.DB.one('SELECT angle FROM team_briefs WHERE id=?',r.brief_id).angle,proposal.angle);assert.equal(JSON.parse(env.DB.one('SELECT proposal_json FROM operator_campaign_promotions').proposal_json).angle,proposal.angle);assert.ok(renderSpine(await buildSpine(env)).includes(proposal.angle));
});
