import {test} from 'node:test';import assert from 'node:assert/strict';
import {createCampaignPreview,onRequestPost,onRequestGet} from '../../functions/api/hub/owner/operator-campaign-preview.js';
import {onRequest as middleware} from '../../functions/api/_middleware.js';
import {ownerEnv,OWNER_COOKIE} from '../helpers/sqlite-d1.js';
const request_id='12345678-1234-4123-8123-123456789abc',idea_id='obi_'+'a'.repeat(64);
const proposal={title:'Private strategy',objective:'Owner review',audience:'Local hosts',angle:'Cajitas',channels:['instagram'],product_ids:[],cadence:'Draft only',success_metric:'Needs confirmation',assets:[],assumptions:[],questions:['Which date?']};
const generated=()=>({ok:true,proposal,actions:[],action:null,review_required:true,model:'mock',input_context:{menu:'supplied',available_product_ids:[]},inference_receipt:{id:'receipt'},inference_attempts:[]});
function fixture(){const env=ownerEnv();env.DB.sqlite.prepare("INSERT INTO operator_brief_ideas VALUES (?, 'Idea','Exact owner words','draft','stf_owner',1,1)").run(idea_id);return env;}
const request=(body,cookie=OWNER_COOKIE)=>new Request('https://anejocateringco.com/api/hub/owner/operator-campaign-preview',{method:'POST',headers:{cookie,'content-type':'application/json'},body:JSON.stringify(body)});
test('claim precedes one inference; concurrent requests observe generating then saved result',async()=>{const env=fixture();let calls=0,release;const wait=new Promise(r=>{release=r;});const generator=async(e,input)=>{calls++;assert.deepEqual(input,{message:'Exact owner words',history:[],mode:'private_campaign_preview'});assert.equal(env.DB.one('SELECT state FROM operator_campaign_previews').state,'generating');await wait;return generated();};const first=createCampaignPreview(env,'stf_owner',{request_id,idea_id},generator);while(!calls)await new Promise(r=>setTimeout(r,1));const pending=await createCampaignPreview(env,'stf_owner',{request_id,idea_id},generator);assert.equal(pending.status,202);assert.equal((await pending.json()).preview.generated,false);release();const saved=await (await first).json();assert.equal(saved.saved,true);assert.equal(saved.preview.proposal.title,proposal.title);assert.equal(saved.preview.source_receipts.inference_receipt.id,'receipt');const retry=await createCampaignPreview(env,'stf_owner',{request_id,idea_id},generator);assert.equal((await retry.json()).saved,true);assert.equal(calls,1);assert.equal(env.DB.one('SELECT COUNT(*) n FROM social_posts').n,0);assert.equal(env.DB.one('SELECT topic FROM operator_campaign_previews').topic,'Exact owner words');});
test('terminal provider failure and uncertain save never rerun inference',async()=>{for(const persistFailure of [false,true]){const env=fixture();let calls=0;const prepare=env.DB.prepare.bind(env.DB);if(persistFailure)env.DB.prepare=sql=>{if(sql.startsWith('UPDATE operator_campaign_previews'))throw Error('storage');return prepare(sql);};const generator=async()=>{calls++;if(persistFailure)return generated();throw Error('provider secret');};const first=await createCampaignPreview(env,'stf_owner',{request_id,idea_id},generator);assert.equal(first.status,persistFailure?503:200);env.DB.prepare=prepare;const retry=await createCampaignPreview(env,'stf_owner',{request_id,idea_id},generator);const body=await retry.json();assert.equal(calls,1);assert.equal(body.preview.generated,false);assert.equal(body.preview.state,persistFailure?'generating':'failed');assert.ok(!JSON.stringify(body).includes('secret'));}});
test('changed idea payload conflicts, another owner cannot access private idea or preview',async()=>{const env=fixture();await createCampaignPreview(env,'stf_owner',{request_id,idea_id},async()=>generated());assert.equal((await createCampaignPreview(env,'stf_owner',{request_id,idea_id:'obi_'+'b'.repeat(64)})).status,409);assert.equal((await createCampaignPreview(env,'other',{request_id,idea_id})).status,404);});
test('forbidden actions or malformed proposal produce terminal failure only',async()=>{for(const value of [{...generated(),actions:[{type:'publish'}]},{...generated(),proposal:{...proposal,approved:true}}]){const env=fixture();const result=await (await createCampaignPreview(env,'stf_owner',{request_id,idea_id},async()=>value)).json();assert.equal(result.preview.state,'failed');assert.equal(result.saved,false);assert.equal(env.DB.one('SELECT COUNT(*) n FROM social_posts').n,0);}});
test('GET distinguishes empty, saved, missing and unreadable private records',async()=>{const env=fixture();const get=query=>onRequestGet({env,request:new Request('https://anejocateringco.com/api/hub/owner/operator-campaign-preview'+query,{headers:{cookie:OWNER_COOKIE}})});assert.deepEqual((await (await get('')).json()).previews,[]);await createCampaignPreview(env,'stf_owner',{request_id,idea_id},async()=>generated());assert.equal((await (await get('?idea_id='+idea_id)).json()).previews.length,1);assert.equal((await (await get('?request_id='+request_id)).json()).saved,true);assert.equal((await get('?id=ocp_'+'0'.repeat(64))).status,404);const prepare=env.DB.prepare.bind(env.DB);env.DB.prepare=sql=>{if(sql.includes('FROM operator_campaign_previews'))throw Error();return prepare(sql);};const failed=await get('');assert.equal(failed.status,503);assert.equal(Object.hasOwn(await failed.json(),'previews'),false);});
test('handler role, CSRF, extra fields and body bounds guard claim',async()=>{const env=fixture();for(const cookie of ['','anejo_sess=tok-marketing','anejo_sess=tok-kitchen'])assert.ok([401,403].includes((await onRequestPost({env,request:request({request_id,idea_id},cookie)})).status));assert.equal((await onRequestPost({env,request:request({request_id,idea_id,activate:true})})).status,400);const req=request({request_id,idea_id});req.headers.set('Origin','https://attacker.example');assert.equal((await middleware({request:req,next:()=>onRequestPost({env,request:req})})).status,403);assert.equal(env.DB.one('SELECT COUNT(*) n FROM operator_campaign_previews').n,0);});
test('actual handler uses private Lead mode with mocked provider and saves proposal without executor writes',async()=>{const env=fixture();env.ANTHROPIC_API_KEY='test';const initialBriefs=env.DB.one('SELECT COUNT(*) n FROM team_briefs').n;const original=globalThis.fetch;let calls=0,body;globalThis.fetch=async(url,options)=>{calls++;body=JSON.parse(options.body);return {ok:true,status:200,json:async()=>({stop_reason:'end_turn',content:[{type:'text',text:JSON.stringify(proposal)}],usage:{input_tokens:10,output_tokens:10}})};};try{const response=await onRequestPost({env,request:request({request_id,idea_id})});const saved=await response.json();assert.equal(saved.saved,true,JSON.stringify(saved));assert.equal(calls,1);assert.equal(body.messages.at(-1).content,'Exact owner words');assert.equal(saved.preview.proposal.title,proposal.title);assert.equal(env.DB.one('SELECT COUNT(*) n FROM social_posts').n,0);assert.equal(env.DB.one('SELECT COUNT(*) n FROM team_briefs').n,initialBriefs);assert.equal((await onRequestPost({env,request:request({request_id,idea_id})})).status,200);assert.equal(calls,1);}finally{globalThis.fetch=original;}});
test('claim storage failure prevents provider invocation and cross-owner GET cannot read preview',async()=>{const env=fixture();let calls=0;const prepare=env.DB.prepare.bind(env.DB);env.DB.prepare=sql=>{if(sql.startsWith('INSERT INTO operator_campaign_previews'))throw Error('storage');return prepare(sql);};assert.equal((await createCampaignPreview(env,'stf_owner',{request_id,idea_id},async()=>{calls++;return generated();})).status,503);assert.equal(calls,0);env.DB.prepare=prepare;const saved=await (await createCampaignPreview(env,'stf_owner',{request_id,idea_id},async()=>generated())).json();const at=Date.now();env.DB.sqlite.prepare("INSERT INTO staff(id,name,email,role,active,created_at,updated_at) VALUES ('other','Other','other@example.test','owner',1,?,?)").run(at,at);await env.SESSIONS.put('session:other',JSON.stringify({type:'staff',uid:'other',role:'owner',la:at,created:at}));const response=await onRequestGet({env,request:new Request('https://anejocateringco.com/api/hub/owner/operator-campaign-preview?id='+saved.preview.id,{headers:{cookie:'anejo_sess=other'}})});assert.equal(response.status,404);});
